name: build
on:
  push:

jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
    #  "jacocoTestReport"をコマンドに追加
        run: ./gradlew build jacocoTestReport
      - name: Archive unit test results
        uses: actions/upload-artifact@v2
        with:
          name: unit-test-report
          path: build/reports/tests/test
    # 以下追記
      - name: Archive coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: build/reports/jacoco/test/html
